# Generated by Django 4.0.5 on 2022-06-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0002_category_location_photo_remove_rating_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image2',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='image3',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
    ]
