# Generated by Django 4.0.5 on 2022-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0003_photo_image2_photo_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image0',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
    ]
