# Generated by Django 4.0.5 on 2022-06-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0004_photo_image0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image0',
            new_name='image4',
        ),
    ]
