# Generated by Django 4.0.5 on 2022-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0005_rename_image0_photo_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image5',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='image6',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='image7',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
    ]
